txt1, starting_day = input().split()
starting_day = int(starting_day)
s_hour, txt2, s_min, txt3, s_second = input().split()
s_hour = int(s_hour)
s_min = int(s_min)
s_second = int(s_second)
txt4, ending_day = input().split()
ending_day = int(ending_day)
e_hour, txt5, e_min, txt6, e_second = input().split()
e_hour = int(e_hour)
e_min = int(e_min)
e_second = int(e_second)
total_second_starting_day = s_second + (s_min*60) + (s_hour*(60*60)) + (starting_day*(24*60*60))
total_second_ending_day = e_second + (e_min*60) + (e_hour*(60*60)) + (ending_day*(24*60*60))
total_left_second = total_second_ending_day - total_second_starting_day
print("{} dia(s)".format(int(total_left_second/(24*60*60))))
print("{} hora(s)".format(int((total_left_second%(24*60*60))/(60*60))))
print("{} minuto(s)".format(int((total_left_second%(24*60*60)%(60*60))/60)))
print("{} segundo(s)".format(int(total_left_second%(24*60*60)%(60*60)%60)))